import Head from 'next/head'
import Modal from './modal'
import styles from '../styles/index.module.css'
import logo from '../public/logo_fi.webp'
import Image from 'next/image'
import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>Inteligencia Financiera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous" />
      </Head>
      <header className={styles.bgBlueHeader}>
        <Image
          src={logo}
          alt="Logo image Inteligencia Financiera"
          height={80}
          width={320}
        />
        <Modal></Modal>
      </header>
      <main className='h-100 d-flex justify-content-center align-items-center mt-4 p-3'>
        <div>
          <div className='container-md container-sm container-xl mt-5'>
            <div className="row">
              <div className="col-12">
                <h1 className='display-3 fw-bolder text-center linktitle'>Bienvenido a <Link className={styles.title} href="https://www.fi-fintech.com/">FI Inteligencia Fianciera</Link>
                </h1>
              </div>
            </div>
          </div>

          <div className="container-fluid my-xl-5">
            <div className="row">

              <div className="col-sm-12 col-xl-6 col-md-12 px-0">
                <Link href="https://www.fi-fintech.com/index.php/invertir/" className='text-decoration-none'>
                <div className={styles.borderLinks}>
                <h4 className='font-bold mb-3 subtitle'>Invierte →</h4>
                <p className='fs-5 parrafo'>Cada inversionista participa en oportunidades de crédito prestando dinero a otras personas y a cambio reciben mejor retorno de los créditos desembolsados.</p>
                </div>
                </Link>
              </div>

              <div className="col-sm-12 col-xl-6 col-md-12 px-0">
                <Link href="https://www.fi-fintech.com/index.php/invertir/" className='text-decoration-none'>
                <div className={styles.borderLinks}>
                <h4 className='font-bold mb-3 subtitle'>Invierte en préstamos de persona a persona →</h4>
                <p className='fs-5 parrafo'>Gana buenos rendimientos prestándole a personas con buen historial crediticio y capacidad de pago comprobada.</p>
                </div>
                </Link>
              </div>

              <div className="col-sm-12 col-xl-6 col-md-12 px-0">
                <Link href="https://www.fi-fintech.com/index.php/simula-tu-prestamo/" className='text-decoration-none'>
                <div className={styles.borderLinks}>
                <h4 className='font-bold mb-3 subtitle'>Simula tu préstamo →</h4>
                <p className='fs-5 parrafo'>¡ Libertad es tener tu credito en 4 pasos, estamos aqui para acompañarte en tu solicitud !</p>
                </div>
                </Link>
              </div>

              <div className="col-sm-12 col-xl-6 col-md-12 px-0">
                <Link href="https://www.fi-fintech.com/index.php/como-funciona/" className='text-decoration-none'>
                <div className={styles.borderLinks}>
                <h4 className='font-bold mb-3 subtitle'>Como Funciona? →</h4>
                <p className='fs-5 parrafo'>Conectamos directamente a personas que necesitan un préstamo con personas que quieren invertir su dinero.</p>
                </div>
                </Link>
              </div>

            </div>
          </div>
        </div>

      </main>
    </>
  )
}
